# Generated by Django 2.2 on 2023-03-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_title', models.CharField(default='', max_length=255)),
                ('role_description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_roll', models.CharField(default='', max_length=225)),
                ('student_name', models.CharField(default='', max_length=225)),
                ('student_email', models.CharField(default='', max_length=255)),
                ('student_phone', models.EmailField(default='', max_length=255)),
                ('student_gender', models.CharField(default='', max_length=10)),
                ('student_dob', models.CharField(default='', max_length=225)),
                ('student_city', models.CharField(default='', max_length=255)),
                ('student_state', models.CharField(default='', max_length=255)),
                ('student_pincode', models.CharField(default='', max_length=255)),
                ('student_course_id', models.CharField(default='', max_length=255)),
                ('student_admission_date', models.CharField(default='', max_length=255)),
                ('student_address', models.TextField(default='')),
                ('student_photo', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
